let itensCarrinho = carregarCarrinho();
const listaHtml = document.getElementById('cart-list');
const totalHtml = document.getElementById('cart-total');
const money = value => `${Number(value || 0).toLocaleString('pt-AO')} Kz`;
function carregarCarrinho(){try{const bruto=JSON.parse(localStorage.getItem('milomercios_cart')||'[]');if(!Array.isArray(bruto))return [];return bruto.map(item=>({...item,quantidade:Math.max(1,Math.floor(Number(item.quantidade)||1)),preco:Number(item.preco)||0,vendedorId:String(item.vendedorId||'').trim()})).filter(item=>item.id&&item.nome&&item.preco>0);}catch{return [];}}
function guardarCarrinho(){localStorage.setItem('milomercios_cart',JSON.stringify(itensCarrinho));}
function renderizarCarrinho(){listaHtml.innerHTML='';let somaTotal=0;if(!itensCarrinho.length){listaHtml.innerHTML='<div class="empty-state"><i class="fas fa-basket-shopping" style="font-size:2.4rem"></i><h3 style="margin:12px 0 5px">O seu carrinho está vazio</h3><p>Explore o catálogo e adicione os produtos que pretende comprar.</p><a class="btn" href="index.html"><i class="fas fa-store"></i> Explorar produtos</a></div>';totalHtml.innerText='0 Kz';return;}itensCarrinho.forEach((item,index)=>{const quantidade=item.quantidade,preco=item.preco,subtotal=preco*quantidade;somaTotal+=subtotal;listaHtml.innerHTML+=`<article class="cart-item"><div><strong>${escapeHtml(item.nome)}</strong><p style="color:var(--muted);font-size:.88rem;margin:3px 0">${money(preco)} por unidade</p><small>${item.vendedorId?'Vendedor associado':'Vendedor não identificado'}</small></div><div style="display:flex;align-items:center;gap:8px;flex-wrap:wrap;justify-content:flex-end"><button aria-label="Diminuir quantidade" onclick="alterarQuantidade(${index},-1)">−</button><strong>${quantidade}</strong><button aria-label="Aumentar quantidade" onclick="alterarQuantidade(${index},1)">+</button><strong style="min-width:100px;text-align:right">${money(subtotal)}</strong><button onclick="removerDoCarrinho(${index})" style="color:red;border:none;background:none;font-weight:bold;cursor:pointer">Remover</button></div></article>`});totalHtml.innerText=money(somaTotal);}
function alterarQuantidade(index,delta){const item=itensCarrinho[index];if(!item)return;item.quantidade=Math.max(1,item.quantidade+Number(delta||0));guardarCarrinho();renderizarCarrinho();}window.alterarQuantidade=alterarQuantidade;
function removerDoCarrinho(index){itensCarrinho.splice(index,1);guardarCarrinho();renderizarCarrinho();}window.removerDoCarrinho=removerDoCarrinho;
function limparCarrinho(){itensCarrinho=[];guardarCarrinho();renderizarCarrinho();}window.limparCarrinho=limparCarrinho;
function escapeHtml(value){return String(value??'').replace(/[&<>'\"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'})[char]);}
renderizarCarrinho();
