import { db } from './firebase-config.js';
import { doc,getDoc,collection,query,where,getDocs } from 'https://www.gstatic.com/firebasejs/10.8.1/firebase-firestore.js';
const esc=v=>String(v??'').replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const money=v=>`${Number(v||0).toLocaleString('pt-AO')} Kz`;
const el=id=>document.getElementById(id);
function cartCount(){const c=JSON.parse(localStorage.getItem('milomercios_cart'))||[];el('cart-count').textContent=c.reduce((t,i)=>t+(Number(i.quantidade)||1),0);}
function add(p){const c=JSON.parse(localStorage.getItem('milomercios_cart'))||[],i=c.find(x=>String(x.id)===String(p.id)),q=Number(i?.quantidade)||0;if(q>=p.stock)return alert(`Só existem ${p.stock} unidades disponíveis.`);if(i)i.quantidade=q+1;else c.push({...p,quantidade:1});localStorage.setItem('milomercios_cart',JSON.stringify(c));cartCount();alert('Produto adicionado ao carrinho.');}
async function carregar(){cartCount();const sellerId=new URLSearchParams(location.search).get('id');const head=el('store-head'),products=el('products');if(!sellerId){head.innerHTML='<div><h1>Loja não encontrada</h1><p>Identificador do vendedor em falta.</p></div>';products.innerHTML='';return;}try{const s=await getDoc(doc(db,'usuarios',sellerId));if(!s.exists()||s.data().tipo!=='vendedor'){head.innerHTML='<div><h1>Loja não encontrada</h1><p>Este vendedor não existe.</p></div>';products.innerHTML='';return;}const v=s.data(),nome=v.nomeLoja||v.nome||'Loja do vendedor';head.querySelector('h1').textContent=nome;head.querySelector('p').textContent='Produtos disponíveis no Milomércios';document.title=`${nome} | Milomércios`;const snap=await getDocs(query(collection(db,'produtos'),where('vendedorId','==',sellerId),where('ativo','==',true)));const lista=snap.docs.map(d=>{const p=d.data();return{id:d.id,nome:p.nome||'Produto sem nome',preco:Number(p.preco||0),stock:Math.max(0,Math.floor(Number(p.stock)||0)),img:p.img||p.imagemUrl||'',descricao:p.descricao||'',vendedorId:sellerId};}).filter(p=>p.preco>0);products.innerHTML=lista.length?lista.map(p=>{const img=p.img?`<img src="${esc(p.img)}" alt="${esc(p.nome)}" loading="lazy">`:'<div class="placeholder"><i class="fas fa-image"></i></div>';return `<article class="store-card">${img}<h3><a href="produto.html?id=${encodeURIComponent(p.id)}">${esc(p.nome)}</a></h3><p class="price">${money(p.preco)}</p><p class="${p.stock?'stock-ok':'stock-out'}">${p.stock?`${p.stock} em stock`:'Esgotado'}</p><button class="btn-buy" ${p.stock?'':'disabled'} data-id="${esc(p.id)}">${p.stock?'Adicionar ao carrinho':'Esgotado'}</button></article>`;}).join(''):'<div class="store-empty"><i class="fas fa-box-open"></i><h3>Nenhum produto publicado</h3><p>Esta loja ainda não tem produtos disponíveis.</p></div>';products.querySelectorAll('button[data-id]').forEach(b=>b.onclick=()=>{const p=lista.find(x=>x.id===b.dataset.id);if(p)add(p);});}catch(e){console.error(e);products.innerHTML='<div class="store-empty"><i class="fas fa-triangle-exclamation"></i><h3>Não foi possível carregar a loja</h3><p>Tente novamente.</p></div>';}}
carregar();
