import { db } from './firebase-config.js';
import { doc, getDoc } from 'https://www.gstatic.com/firebasejs/10.8.1/firebase-firestore.js';
const el=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const money=v=>`${Number(v||0).toLocaleString('pt-AO')} Kz`;
let produto=null, quantidade=1;
function atualizarCarrinho(){const cart=JSON.parse(localStorage.getItem('milomercios_cart'))||[];el('cart-count').textContent=cart.reduce((t,i)=>t+(Number(i.quantidade)||1),0);}
function adicionar(){if(!produto||produto.stock<1)return alert('Este produto está esgotado.');const cart=JSON.parse(localStorage.getItem('milomercios_cart'))||[],item=cart.find(i=>String(i.id)===String(produto.id)),atual=Number(item?.quantidade)||0;if(atual+quantidade>produto.stock)return alert(`Só existem ${produto.stock} unidades disponíveis.`);if(item)item.quantidade=atual+quantidade;else cart.push({...produto,quantidade});localStorage.setItem('milomercios_cart',JSON.stringify(cart));atualizarCarrinho();alert('Produto adicionado ao carrinho.');}
function render(){const box=el('produto');if(!produto){box.className='notice';box.innerHTML='<i class="fas fa-box-open"></i><h2>Produto não encontrado</h2><p>Este produto pode ter sido removido ou ainda não foi aprovado.</p>';return;}const disponivel=produto.stock>0,imagem=produto.img?`<img class="detail-image" src="${esc(produto.img)}" alt="${esc(produto.nome)}">`:'<div class="detail-image placeholder"><i class="fas fa-image"></i></div>';box.className='detail-card';box.innerHTML=`<div>${imagem}</div><div class="detail-info"><span class="section-kicker">${esc(produto.categoria)}</span><h1>${esc(produto.nome)}</h1><div class="detail-price">${money(produto.preco)}</div><div class="detail-stock ${disponivel?'stock-ok':'stock-out'}">${disponivel?`<i class="fas fa-circle-check"></i> ${produto.stock} unidades disponíveis`:'<i class="fas fa-circle-xmark"></i> Produto esgotado'}</div><p class="detail-description">${esc(produto.descricao||'Sem descrição disponível.')}</p><div class="detail-actions"><div class="qty"><button id="menos" type="button">−</button><span id="quantidade">1</span><button id="mais" type="button">+</button></div><button id="add" class="btn-buy" ${disponivel?'':'disabled'}><i class="fas fa-cart-plus"></i> Adicionar ao carrinho</button></div><div class="store-box"><strong><i class="fas fa-store"></i> Loja do vendedor</strong><p style="color:var(--muted);margin:4px 0 10px">Veja outros produtos deste vendedor.</p><a class="btn" href="loja.html?id=${encodeURIComponent(produto.vendedorId)}">Visitar loja</a></div></div>`;el('menos').onclick=()=>{quantidade=Math.max(1,quantidade-1);el('quantidade').textContent=quantidade;};el('mais').onclick=()=>{quantidade=Math.min(produto.stock,quantidade+1);el('quantidade').textContent=quantidade;};el('add').onclick=adicionar;}
async function carregar(){atualizarCarrinho();const id=new URLSearchParams(location.search).get('id');if(!id)return render();try{const snap=await getDoc(doc(db,'produtos',id));if(!snap.exists()||snap.data().ativo!==true)return render();const d=snap.data();produto={id:snap.id,nome:d.nome||'Produto sem nome',preco:Number(d.preco||0),stock:Math.max(0,Math.floor(Number(d.stock)||0)),categoria:String(d.categoria||'outros'),descricao:d.descricao||'',img:d.img||d.imagemUrl||'',vendedorId:d.vendedorId||''};document.title=`${produto.nome} | Milomércios`;render();}catch(e){console.error(e);el('produto').innerHTML='<i class="fas fa-triangle-exclamation"></i><h2>Não foi possível carregar o produto</h2><p>Tente novamente.</p>';}}
carregar();
