-- Milomércios: campanhas, cliques e atribuição de conversões.
-- Executar no SQL Editor do projeto Supabase antes de usar os links de rastreio.

create table if not exists public.campaigns (
  id uuid primary key default gen_random_uuid(),
  vendedor_id uuid not null references auth.users(id) on delete cascade,
  produto_id uuid not null references public.products(id) on delete cascade,
  nome text not null,
  objetivo text,
  publico text,
  canais text[] default '{}',
  titulo text,
  texto text,
  chamada text,
  estado text not null default 'rascunho',
  cliques integer not null default 0,
  conversoes integer not null default 0,
  criado_em timestamptz not null default now()
);

alter table public.campaigns enable row level security;

create index if not exists campaigns_vendedor_id_idx on public.campaigns(vendedor_id);
create index if not exists campaigns_produto_id_idx on public.campaigns(produto_id);

create table if not exists public.campaign_clicks (
  id bigint generated by default as identity primary key,
  campaign_id uuid not null references public.campaigns(id) on delete cascade,
  produto_id uuid not null references public.products(id) on delete cascade,
  canal text not null default 'outro',
  session_id text not null,
  user_id uuid references auth.users(id) on delete set null,
  criado_em timestamptz not null default now()
);

create index if not exists campaign_clicks_campaign_id_idx on public.campaign_clicks(campaign_id);
create index if not exists campaign_clicks_session_id_idx on public.campaign_clicks(session_id);

alter table public.campaign_clicks enable row level security;

-- O cliente pode chamar apenas a função pública de rastreio; não precisa de INSERT direto.
create or replace function public.registar_clique_campanha(
  p_campaign_id uuid,
  p_product_id uuid,
  p_channel text,
  p_session_id text
) returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  campanha public.campaigns%rowtype;
begin
  select * into campanha
  from public.campaigns
  where id = p_campaign_id and produto_id = p_product_id;

  if not found then
    return;
  end if;

  -- Evita contar duas vezes o mesmo clique da mesma sessão para a mesma campanha.
  if exists (
    select 1 from public.campaign_clicks
    where campaign_id = p_campaign_id and session_id = p_session_id
  ) then
    return;
  end if;

  insert into public.campaign_clicks(campaign_id, produto_id, canal, session_id, user_id)
  values (p_campaign_id, p_product_id, left(coalesce(p_channel, 'outro'), 40), left(p_session_id, 120), auth.uid());

  update public.campaigns
  set cliques = cliques + 1
  where id = p_campaign_id;
end;
$$;

grant execute on function public.registar_clique_campanha(uuid, uuid, text, text) to anon, authenticated;

create or replace function public.registar_conversao_campanha(
  p_campaign_id uuid,
  p_session_id text
) returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if p_campaign_id is null or p_session_id is null or length(p_session_id) = 0 then
    return;
  end if;

  if exists (
    select 1 from public.campaign_clicks
    where campaign_id = p_campaign_id and session_id = p_session_id
  ) then
    update public.campaigns
    set conversoes = conversoes + 1
    where id = p_campaign_id;
  end if;
end;
$$;

grant execute on function public.registar_conversao_campanha(uuid, text) to authenticated;

-- Vendedores veem e gerem apenas as próprias campanhas.
drop policy if exists "campaigns_select_own" on public.campaigns;
create policy "campaigns_select_own" on public.campaigns for select to authenticated using (vendedor_id = auth.uid());

drop policy if exists "campaigns_insert_own" on public.campaigns;
create policy "campaigns_insert_own" on public.campaigns for insert to authenticated with check (vendedor_id = auth.uid());

drop policy if exists "campaigns_update_own" on public.campaigns;
create policy "campaigns_update_own" on public.campaigns for update to authenticated using (vendedor_id = auth.uid()) with check (vendedor_id = auth.uid());

-- Cliques ficam privados; os contadores são atualizados pelas funções SECURITY DEFINER.
drop policy if exists "campaign_clicks_select_own" on public.campaign_clicks;
create policy "campaign_clicks_select_own" on public.campaign_clicks for select to authenticated
using (exists (select 1 from public.campaigns c where c.id = campaign_id and c.vendedor_id = auth.uid()));
